---
on:
  push:
    tags:
      - '*'

name: Publish tagged image to Docker Hub

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          COMMIT_SHA: ${{ github.sha }}
        with:
          name: getmeili/meilisearch
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
